package com.fairtrack.app.ui.theme

import androidx.compose.ui.graphics.Color

// FairTrack-Markenpalette (grüner Seed ~#3B6939), erzeugt nach dem
// Material-Theme-Builder-Schema. Gilt immer — Material You wird erst
// in v0.11.0 als Opt-in angeboten.

// Light
val LightPrimary = Color(0xFF3B6939)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBCF0B4)
val LightOnPrimaryContainer = Color(0xFF235024)
val LightSecondary = Color(0xFF52634F)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD5E8CF)
val LightOnSecondaryContainer = Color(0xFF3A4B39)
val LightTertiary = Color(0xFF38656A)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFBCEBF0)
val LightOnTertiaryContainer = Color(0xFF1E4D52)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)
// Neutrale (ungetönte) Flächen im MyFitnessPal-Stil: hellgrauer Hintergrund,
// reinweiße Cards — Farbe kommt nur über die Akzente.
val LightBackground = Color(0xFFFAFAFA)
val LightOnBackground = Color(0xFF1A1C1A)
val LightSurface = Color(0xFFFAFAFA)
val LightOnSurface = Color(0xFF1A1C1A)
val LightSurfaceVariant = Color(0xFFEDEEED)
val LightOnSurfaceVariant = Color(0xFF454745)
val LightOutline = Color(0xFF757775)
val LightOutlineVariant = Color(0xFFC6C8C6)
val LightScrim = Color(0xFF000000)
val LightInverseSurface = Color(0xFF2F312F)
val LightInverseOnSurface = Color(0xFFF1F1F1)
val LightInversePrimary = Color(0xFFA1D39A)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFFFFFFF)
val LightSurfaceContainer = Color(0xFFF1F2F1)
val LightSurfaceContainerHigh = Color(0xFFEBEDEB)
val LightSurfaceContainerHighest = Color(0xFFE5E7E5)

// Dark
val DarkPrimary = Color(0xFFA1D39A)
val DarkOnPrimary = Color(0xFF0A390F)
val DarkPrimaryContainer = Color(0xFF235024)
val DarkOnPrimaryContainer = Color(0xFFBCF0B4)
val DarkSecondary = Color(0xFFB9CCB4)
val DarkOnSecondary = Color(0xFF243424)
val DarkSecondaryContainer = Color(0xFF3A4B39)
val DarkOnSecondaryContainer = Color(0xFFD5E8CF)
val DarkTertiary = Color(0xFFA0CFD4)
val DarkOnTertiary = Color(0xFF00363B)
val DarkTertiaryContainer = Color(0xFF1E4D52)
val DarkOnTertiaryContainer = Color(0xFFBCEBF0)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF141414)
val DarkOnBackground = Color(0xFFE3E3E3)
val DarkSurface = Color(0xFF141414)
val DarkOnSurface = Color(0xFFE3E3E3)
val DarkSurfaceVariant = Color(0xFF444746)
val DarkOnSurfaceVariant = Color(0xFFC4C7C5)
val DarkOutline = Color(0xFF8E918F)
val DarkOutlineVariant = Color(0xFF444746)
val DarkScrim = Color(0xFF000000)
val DarkInverseSurface = Color(0xFFE3E3E3)
val DarkInverseOnSurface = Color(0xFF303030)
val DarkInversePrimary = Color(0xFF3B6939)
val DarkSurfaceContainerLowest = Color(0xFF0F0F0F)
val DarkSurfaceContainerLow = Color(0xFF1D1D1D)
val DarkSurfaceContainer = Color(0xFF212121)
val DarkSurfaceContainerHigh = Color(0xFF2B2B2B)
val DarkSurfaceContainerHighest = Color(0xFF363636)
